- name: Install MicroK8s
  become: true
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_version }}"

- name: Add login user to microk8s group
  become: yes
  user:
    name: "{{ microk8s_user }}"
    group: microk8s
    append: true

- name: reset ssh connection
  meta: reset_connection

- name: Wait for microk8s to be ready
  become: true
  command: /snap/bin/microk8s.status --wait-ready --timeout 5
  changed_when: False
  register: output_microk8s_install_wait
  until: output_microk8s_install_wait.stdout is search("microk8s is running") or output_microk8s_install_wait.stdout is search("deployment is acting as a node in a cluster")
  retries: 10
  delay: 5

- name: Create kubectl alias
  become: yes
  command: "snap alias microk8s.kubectl kubectl"
  changed_when: false
  register: aliaskubectlout

- name: Create helm3 alias
  become: yes
  command: "snap alias microk8s.helm3 helm"
  changed_when: false
  register: aliashelmout
  when:
    - "'helm3' in microk8s_plugins"
    - microk8s_plugins.helm3

# Must check how to get 'novalocal' from a proper source, so it is not hardcoded
# TODO
- name: Enumerate all cluster hosts within the hosts file
  become: yes
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: microk8s HA Cluster Hosts"
    content: |
      {% for host in groups['master'] %}
      {{ hostvars[host].ansible_default_ipv4.address }} {{ hostvars[host].ansible_hostname }} {{ hostvars[host].ansible_hostname }}.novalocal
      {% endfor %}
      {% if 'compute' in groups %}
      {% for host in groups['compute'] %}
      {{ hostvars[host].ansible_default_ipv4.address }} {{ hostvars[host].ansible_hostname }} {{ hostvars[host].inventory_hostname }}.novalocal
      {% endfor %}
      {% endif %}
