---
- name: Run Terraform
  terraform:
    project_path: "{{ playbook_dir }}/terraform"
    state: present
    workspace: default
    # Here we can override variables defined within the Terraform modules
    # Note that all variables that we want to override need to be present
    # in main.tf, even though they might be defined in a module
    # TODO Should be able to add variables to Terraform
    #variables:
    #  instance_count: 2
  register: tf_results

# Now iterate over the list returned by Terraform and build
# the inventory accordingly.
- name: Add entries to inventory
  add_host:
    name: "{{ item.name }}"
    ansible_ssh_host: "{{ item.ip }}"
    ansible_ssh_user: "{{item.ansible_ssh_user}}"
    ansible_ssh_private_key_file: "{{item.private_key_file}}"
    host_key_checking: no
    groups: "{{ item.groups }}"
    ansible_ssh_common_args: "{{item.ssh_args}}"
  loop: "{{ tf_results.outputs.inventory.value }}"

- name: Master IP
  debug:
    msg: "Master IP: {{ item.ip }}"
  loop: "{{ tf_results.outputs.inventory.value }}"
  when: item.groups == "['master']"
